### PR TITLE
astrooda -> mmoda

### PR DESCRIPTION
**Pull request by dsavchenko**

### CODE REVIEW

**Comment by dsavchenko** [comment]
How is _version.yaml_ used?

**Comment by motame** [comment]
version.yaml is not used in Drupal 7 or at least I do not use it.

**Comment by dsavchenko** [comment]
There are few mentions of Astrooda left in the READMEs concerning help pages. All of them are related to the old realisation, as I understand. Need to sort this out. @motame

The question about version.yaml is addressed to @volodymyrss The file also contains old repository links. I see that this file is used in GitLab CI/CD. At what point should we change it?

**Comment by volodymyrss** [comment]
> There are few mentions of Astrooda left in the READMEs concerning help pages. All of them are related to the old realisation, as I understand. Need to sort this out. @motame 

Yes please! These pages are copied over from old redmine wiki. Could they be revised and maybe trimmed ?

> The question about version.yaml is addressed to @volodymyrss The file also contains old repository links. I see that this file is used in GitLab CI/CD. At what point should we change it?

I deleted and ignored it. It can be generated.

**Pull request closed without merging**
